services:
  url-shortner:
    image: ahmedghanem111/url-shortner:v1.0
    ports:
      - "8080:8080"
    depends_on:
      - redis-db
    environment:
      - ConnectionStrings__Redis=redis-db:6379
  redis-db:
    image: redis:8.2-alpine
    ports:
      - "6390:6379"
  redis-insight:
    image: redislabs/redisinsight
    ports:
      - "5540:5540"