apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner
  namespace: url-shortner-ns
spec:
  selector:
    matchLabels:
      app: url-shortner
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
        - name: url-shortner
          image: ahmedghanem111/url-shortner:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__Redis
              value: redis:6379
